### ISSUE TITLE
[스크럼] 2020.06.09 (화) 

### ISSUE THREAD

**Issue by choisohyun** [codesquad-member-2020/issue-tracker-08#15]
### 스크럼 올리는 내용

- 어제 한 일
- 오늘 할 일
- 오늘 컨디션

**Comment by choisohyun** [comment]
## 어제 한 일

- 1주차 요구 사항 정리
- 개발 환경 셋팅
- 구조 설계
- 상태 관리 의논
- 강의 듣기 & qna 질문 생각하기
- 회고

## 오늘 할 일

- 수업(오후 2시~)
(페어 작업)
- 스타일 테마 작업(참고 - ed)(오전 11시~)
- 로그인 화면 UI 작업
- 이슈 목록 화면 틀 UI 작업

## 오늘 컨디션

- 집에서 하는 날 & 프로젝트 초반이라 여유롭습니다.
- 이번주는 화면에 보이는 UI 작업을 많이 할 생각입니다! 모두 화이팅하세요 ^^

**Comment by sally4405** [comment]
## 어제 한 일

- 1주차 요구 사항 정리
- 개발 환경 셋팅
- 구조 설계
- 상태 관리 의논
- 강의 듣기 & qna 질문 생각하기
- 회고

## 오늘 할 일

- 수업(오후 2시~)
(페어 작업)
- 스타일 테마 작업(참고 - ed)(오전 11시~)
- 로그인 화면 UI 작업
- 이슈 목록 화면 틀 UI 작업

## 오늘 컨디션

- 잠을 제대로 못자서 조금 졸립니다..
- 짝페어와 분업을 둘 다 해볼 거 같은데 잘됐으면 좋겠습니다! 다들 화이팅~~

**Comment by beginin15** [comment]
(@hsik0225 과 동일, 각자 작업하는 부분이 발생하면 각자 올리겠습니다!)

## 어제 한 일
- 수업 듣기
- 그라운드 룰 정하기
- 페어와 룰 정하기

## 오늘 할 일
- DB 스키마 설계 (페어와 함께)
- 대략적인 API 설계 (페어와 함께)

## 오늘 컨디션
- 어제 몸이 안좋아서 오늘 늦게 일어났더니 괜찮아진 것 같아요.
