### ISSUE TITLE
[BE] DB 설계

### ISSUE THREAD

**Issue by hsik0225** [codesquad-member-2020/issue-tracker-08#18]
### ERD

![issue-trakcer_02](https://user-images.githubusercontent.com/33659848/84238670-63d97200-ab36-11ea-8408-bbe8ef64801e.png)

**Comment by beginin15** [comment]
2차
![issue-tracker-03](https://user-images.githubusercontent.com/33659848/84783811-926ab780-b024-11ea-9147-af037e690ec9.png)

**Comment by hsik0225** [comment]
3차
![IssueTracker](https://user-images.githubusercontent.com/56301069/84997365-75032e00-b189-11ea-87ed-9237680aa3d1.png)
