### ISSUE TITLE
[FE] 컨벤션 논의

### ISSUE THREAD

**Issue by choisohyun** [codesquad-member-2020/issue-tracker-08#23]
### 적용된 컨벤션

> 적용된 컨벤션은 prettierrc를 통해 일치시킴

- 함수 전후로 개행
- 탭 2칸씩
- 문장 끝에 세미콜론 사용
- 문자열은 “” 사용
—-
- 스타일 코드는 아래로 내리기
- 스타일은 같이 만든 테마와 스타일 최대한 활용하기

### 의논할 컨벤션

- 스타일 코드를 export 밑으로 내릴지, 위에 둘지
- import 순서 , import해오는 것이 많을 때 개행 여부 등
- 리액트 랜더 함수에서 태그로 한 번 감쌀 때 <></> <div> <Wrapper> <Wrap> 중 어떤 것으로 통일해서 감쌀지
- 주석과 console log 코드 
- 스타일 코드 순서?

> 의논 후 코멘트로 기록 예정

**Comment by sally4405** [comment]
### 새롭게 적용된 컨벤션

- 스타일 코드를 export 위에서 작성
- import 순서 (라이브러리, 재사용 스타일, 컴포넌트)
- 리액트 랜더 함수에서 태그로 한 번 감쌀 때 <></> 사용
- 주석과 console log 코드 지우기 (사용 가능성 있는 주석은 설명과 함께 남기기)

**Comment by choisohyun** [comment]
### 상태관리 할 때의 규칙

- 어떻게 비슷한 틀로 정할 수 있을지 생각해 보기

**Comment by choisohyun** [comment]
테스트
