### ISSUE TITLE
[스크럼] 2020.06.10 (수)

### ISSUE THREAD

**Issue by choisohyun** [codesquad-member-2020/issue-tracker-08#24]
### 스크럼 올리는 내용

- 어제 한 일
- 오늘 할 일
- 오늘 컨디션

**Comment by choisohyun** [comment]
# Sally & Hoo

### 어제 한 일 

- 스타일 테마 작업 #19 
- 이슈 목록 화면 #21 (Hoo)
- 로그인/회원가입 화면 #22 (Sally)

### 오늘 할 일 

- 컨벤션 논의 
- 라우팅 작업 
- 이슈 목록 화면 - button component
- 새로운 이슈 쓰기 화면

### 컨디션

- Sally - 지금은 안 졸린데 곧 졸릴 예정입니다.
- Hoo - 이미 제정신 아님..^^ 열심히 해보겠습니다..

**Comment by choisohyun** [comment]
hide

**Comment by beginin15** [comment]
# Ever & Jay

## 어제 한 일

- DB 설계
- BE끼리 API 의논 
- 서버 테스트

## 오늘 할 일

- TEAM에서 API 의논
- 프로젝트 셋팅
- Mock API 구현


## 컨디션

- Ever - 잠을 많이 안자서 피곤하네요 
- Jay - 좋아요
