### ISSUE TITLE
[스크럼] 2020.06.11 (목)

### ISSUE THREAD

**Issue by choisohyun** [codesquad-member-2020/issue-tracker-08#39]
### 스크럼 올리는 내용

- 어제 한 일
- 오늘 할 일
- 오늘 컨디션

### 코멘트 양식

```
### 어제 한 일
-

### 오늘 할 일
-

### 오늘 컨디션
- 
```

**Comment by choisohyun** [comment]
### 어제 한 일
#### 공통 작업
1. 그저께 나눠서 작업한 로그인/이슈목록 화면을 합치는 작업 #21 
2. 코딩 컨벤션을 자세하게 정하고 스타일이 동일해 지도록 수정 #23 
3. 라우팅 처리(history 처리도 함께 함) #28 
4. material ui 으로 필터버튼 이슈목록화면에 적용 #31 

#### 분담 작업
**@sally4405**  
- 마크다운 라이브러리 알아보기
- 테이블 재사용 컴포넌트 작성 #36 

**@choisohyun**  
- 이미지 업로드 api, library 알아보기
- 헤더 재사용 컴포넌트 작성 #33 
- FilterVerticalList (재사용 컴포넌트) 작성 #38 

### 오늘 할 일
- 새로운 이슈 쓰기 화면 작성
- 이슈 상세 화면 작성
(어제 만든 재사용 컴포넌트 사용)
- Label List 화면 작성

### 오늘 컨디션  
**@sally4405**   
- 자꾸 늦게 자버릇 하다보니 페어 시간 맞추는게 어렵네요ㅠㅠ 앞으로 더 일찍 자도록 노력해야겠습니다! 
- 생각보다 markdown editor가 종류도 많고 어려웠는데 너무 완벽하게 많은 기능을 넣으려고 하지말고 시간 조절 하면서 기능을 타협해야 할 것 같습니다! 😢 

**@choisohyun**  
- 지난번 프로젝트때 마지막에 시간이 너무 없게끔 계획을 짰던 것 같아 이번에는 일정을 좀 빡빡하게 잡았는데 그래서 그런지 힘드네요 😵 일단 UI 구성이 이번주 목표였으니 너무 완벽하게 하려고 하지 말아야 겠습니다..  
- 페어 + 작은 단위로 분업하는 것은 지난번 프로젝트와는 다른 새로운 도전이었습니다. 분업하기 위해서는 페어로 할 때보다 정해야 할 것이 많고 기반이 되는 컴포넌트, 스타일이 있을수록 스타일 통일과 빠른 진행에 도움이 되는 것 같습니다!  
- 이번에 재사용 스타일과 재사용 컴포넌트를 처음 제대로 만들어 봤는데, 되게 힘든데 만들어 두니 쓰기가 편해서 재미있습니다 ㅎㅎ
- 내일만 지나면 주말이니 힘을 더 내 보도록 하겠습니다 백엔드도 세세한 요구사항이많아서 할일이 많으실거같은데 화이팅하세요!!

**Comment by beginin15** [comment]
## BE

### 어제 한 일
- 프로젝트 세팅 #27
- Mockup API 구현 진행중 #29

### 오늘 할 일
#### 공통
- Mockup API 구현 완료 #29

#### @hsik0225 
- Github Action을 이용한 자동배포 #37

#### @beginin15 
- Mockup API 검토 #29
- 프로젝트 세팅 중 개발 환경에서 사용할 DB 접속 정보 수정 (각자 로컬 docker의 mysql을 사용하는 방향으로)

### 오늘 컨디션
#### @beginin15 
- 페어를 하다보니 Ever가 alias를 잘 사용하더라구요. 저도 자주 사용하는 명령어는 alias를 지정해보려고 합니다.
- 몸 상태는 조금 피곤하네요...!
