### ISSUE TITLE
[스크럼] 2020.06.12 (금)

### ISSUE THREAD

**Issue by choisohyun** [codesquad-member-2020/issue-tracker-08#47]
### 스크럼 올리는 내용

- 어제 한 일
- 오늘 할 일
- 오늘 컨디션

### 코멘트 양식

```
### 어제 한 일
-

### 오늘 할 일
-

### 오늘 컨디션
-
```

**Comment by choisohyun** [comment]
### 어제 한 일

#### 분담 작업
**@sally4405**  
- 새로운 이슈 쓰기 페이지 #45 
- 라벨 목록 페이지 #46 

**@choisohyun**  
-  이슈 상세 페이지(코멘트 / 필터버튼리스트) 작성 #42 
-  New Label 컴포넌트 작성 #43 

### 오늘 할 일

- Milestone 화면 #7
- New Milestone 화면 #8

### 오늘 컨디션  
**@sally4405**   
- 3시간 정도밖에 못잤더니 정신이 없네요ㅠㅠ 갑자기 다른조꺼 발표라니 발표라니ㅣㅣ
- 생각보다 UI 작업에 시간이 많이 걸리는거 같다고 생각했는데 재사용 컴포넌트들을 만들면서 작업하다보니 오래 걸리는 거 같습니다. 그래도 재사용 컴포넌트들을 만드는게 좋은 경험이 되고 있는거 같아요!
- 주말에는 쉬면서  debounce, redux thunk 같은 것들 공부해볼 예정입니다.

**@choisohyun**  
- 지난 프로젝트에 비해 일을 거의 두 배로 하고 있어서 힘들지만 재사용 컴포넌트를 만들고 쓰면서 발전시켜(?) 나가는게 재미있습니다. 근데 잠을 원래대로 못자니까 이제 정신이 없네요.. 3샷 먹으며 몸부림 치는 나의모습... 이상한 폴더 가서 작업하는 나의 모습.. 다음주에는 이번주 계획의 80%정도만 계획으로 잡아야 살 수 있을 것 같아요.
- 재사용 스타일과 재사용 컴포넌트를 여러개 만들었는데, display flex justify content align items와 같이 정렬할 때 자주 사용되는 스타일 속성을 따로 묶어서 불러오기만 하면 여러 컴포넌트에서 쓰이게 해도 좋을 것 같다는 생각이 듭니다.
- 이번주는 UI 기준으로 되어 있어서 스타일 위주로 컨벤션을 정했는데 다음주부터는 api를 사용하게 될 것 같아서 비동기 작업할 때 규칙이라던가 상태관리할 때의 규칙을 정해 두면 좋을 것 같은데 아직 어떻게 정할지는 감은 안오네요.
- 주말에는 리프레시하고 debounce, redux thunk 사용법을 간단하게 살펴볼예정입니다.

**Comment by beginin15** [comment]
### 어제 한 일

@hsik0225 
- Github Action을 이용한 BE 자동 배포 (FE 배포 진행중) #37 

@beginin15 
- Mockup API 검토 및 추가 #29

### 오늘 할 일

@hsik0225 
- FE 자동 배포 완성 #37

#### 공통
- Github OAuth 로그인 구현 #30 

### 오늘 컨디션

@hsik0225 
- 🤖 

@beginin15 
- 본격적인 기능 분담을 안해서 그런지 긴장감이 부족한 상태인 것 같아요. 다음 주에는 좀 더 분발하겠습니다!
