### ISSUE TITLE
[스크럼] 2020.06.15 (월)

### ISSUE THREAD

**Issue by choisohyun** [codesquad-member-2020/issue-tracker-08#51]
### 스크럼 올리는 내용

- 어제 한 일
- 오늘 할 일
- 오늘 컨디션

### 코멘트 양식

```
### 어제 한 일
-

### 오늘 할 일
-

### 오늘 컨디션
-
```

**Comment by choisohyun** [comment]
### 오늘 할 일

#### 공통 작업
- 스타일 리팩토링 #53 #54 
- [2주차 계획 작성](https://github.com/codesquad-member-2020/issue-tracker-08/wiki/FE-2%EC%A3%BC%EC%B0%A8-%EA%B3%84%ED%9A%8D)
- 공부

### 오늘 컨디션
**@sally4405**   
- 🍏

**@choisohyun**  
- 토요일부터 생활리듬이 무너져서 낮에 살짝 집중이 안되고 있습니다.. 실습위주로 공부를 해서 집중을 해 보겠습니다 화이팅!

**Comment by beginin15** [comment]
### 오늘 할 일
#### 공통 작업
- Mock API, Github OAuth 로그인 배포
- 전반적인 패키지, 도메인 클래스 정의
- Issue 관련 API 구현

### 오늘 컨디션
@beginin15 
- 잠을 많이 못자서 조금 졸리지만 페어 작업하면 괜찮을 것 같아요!

@hsik0225 
- 😼
