### ISSUE TITLE
[스크럼] 2020.06.16 (화)

### ISSUE THREAD

**Issue by beginin15** [codesquad-member-2020/issue-tracker-08#56]
### 스크럼 올리는 내용

- 어제 한 일
- 오늘 할 일
- 오늘 컨디션

### 코멘트 양식

```
### 어제 한 일
-

### 오늘 할 일
-

### 오늘 컨디션
-
```

**Comment by beginin15** [comment]
### 어제 한 일
- Mock API, Github 로그인 배포
- 도메인 클래스 정의
- POST `/label` api 구현

### 오늘 할 일
- `issue` 관련 api 구현
- 기능 분담

### 컨디션
@beginin15 
- 좋아요~

@hsik0225 
- 👍

**Comment by sally4405** [comment]
### 어제 한 일
- 2주차 계획, issue 작성
- 개인 공부 (redux thunk, debounce)

### 오늘 할 일
- qna 수업
- 상태관리 설계
- 데이터 요청 custom hook

### 오늘 컨디션
@choisohyun 
- 💓   

@sally4405 
- 잠을 제대로 못잤습니다ㅠㅠ
