### ISSUE TITLE
[스크럼] 2020.06.17 (수)

### ISSUE THREAD

**Issue by sally4405** [codesquad-member-2020/issue-tracker-08#62]
### 스크럼 올리는 내용

- 어제 한 일
- 오늘 할 일
- 오늘 컨디션

### 코멘트 양식

```
### 어제 한 일
-

### 오늘 할 일
-

### 오늘 컨디션
-
```

**Comment by sally4405** [comment]
### 어제 한 일

#### 공통 작업
- issue list 화면 redux-thunk 연결 #59 

### 오늘 할 일

#### 분담 작업
**@sally4405**  
- 마일스톤 페이지 CRUD API 연결 #64

**@choisohyun**  
-  라벨 페이지 CRUD API 연결 #63 

### 오늘 컨디션  
**@sally4405**   
- 좋습니다~

**@choisohyun**  
- 본격적인 데이터 연결이 시작되었습니다 ! 어렵지만 성능 최적화를 꼭 적용시켜서 더 만족도 있는 웹을 만들고 싶습니다~ 컨디션은 집에 손님이 와서 조금 정신이 없지만 즐겁습니다 ^^

**Comment by beginin15** [comment]
### 어제 한 일
#### 공통
- 각자 JPA와 DDD 공부
- ERD 수정

### 오늘 할 일
#### 공통
- 각자 공부한 것 공유하기
- 연관 관계 설계하기

### 오늘 컨디션
@beginin15 
- 피로가 누적되어서 조금 피곤합니다...

@hsik0225 
- 📖
