### ISSUE TITLE
[스크럼] 2020.06.19

### ISSUE THREAD

**Issue by beginin15** [codesquad-member-2020/issue-tracker-08#73]
### 스크럼 올리는 내용

- 어제 한 일
- 오늘 할 일
- 오늘 컨디션

### 코멘트 양식

```
### 어제 한 일
-

### 오늘 할 일
-

### 오늘 컨디션
-
```

**Comment by beginin15** [comment]
### 어제 한 일

#### 공통
- 도메인 클래스 설계

@hsik0225 
- issue 생성 API 구현 #55

### 오늘 할 일
@beginin15 
- 라벨 생성 API 구현 #57
- 라벨 목록 API 구현 #57
- 마일스톤 생성 API 구현 #58
- 마일스톤 목록 API 구현 #58

### 오늘 컨디션(회고)
@beginin15 
- JPA 사용법을 잘 모르는 상태에서 DDD를 추구하려니까 어렵네요. 공부하려고 인강이나 책을 읽으려고 하면 자꾸 졸려요...😢 

@hsik0225 
- 오늘 낮까지 불태우고 자러갔습니다. 에버 화이팅 (by.Jay)

**Comment by choisohyun** [comment]
저번주에 스크럼과 회고를 제대로 안했네요.. 담주엔 정신차려서 챙겨보겠습니당...
