### ISSUE TITLE
[스크럼] 2020.06.22 (월)

### ISSUE THREAD

**Issue by choisohyun** [codesquad-member-2020/issue-tracker-08#82]
### 스크럼 올리는 내용

- 어제 한 일
- 오늘 할 일
- 오늘 컨디션

### 코멘트 양식

```
### 어제 한 일
-

### 오늘 할 일
-

### 오늘 컨디션
-
```

**Comment by choisohyun** [comment]
### 어제 한 일
@choisohyun  
- 알고리즘 문제풀기
- 리덕스 thunk 원리 이해하고 crud 예제 보고 따라해 보기

### 오늘 할 일
#### 공통
- 로그인 / 회원가입 구현하기 

### 오늘 컨디션
@choisohyun  
- 저번주부터 정신이 다른데 가있는것같습니다.. 정신 차리고 마지막 프로젝트 잘 마무리 했으면 좋겠습니다~~ 
- 이번주에는 부디 최적화 한번쯤은 성공해 봤으면 좋겠습니다 !

**Comment by beginin15** [comment]
### 주말에 한 일
@beginin15 
- 마일스톤 API 일부 구현 #58 

@hsik0225 
- 라벨 API 구현 #57 
- 코멘트 API 구현 #69 

### 오늘 할 일
#### 공통
- 이슈 API 진행 #55 
- 수업 듣기

### 오늘 컨디션
@beginin15 
- 어제 늦게 자서 조금 피곤하네요. 남은 시간은 학원에 계속 나올 수 있으니까 규칙적으로 생활하려고 노력해야겠어요

@hsik0225 
- 🚀
